import React, { useRef } from 'react';
import InputPanel from '../components/InputPanel';
import ResultPanel from '../components/ResultPanel';
import { useDebtCalculator } from '../hooks/useDebtCalculator';
import './Page.css';

export default function ScannerPage() {
  const resultRef = useRef(null);
  const {
    income, setIncome,
    expenses, setExpenses,
    loans, addLoan, removeLoan,
    newAmount, setNewAmount,
    newRate, setNewRate,
    newTenure, setNewTenure,
    result,
    calculate,
  } = useDebtCalculator();

  const exportPDF = async () => {
    if (!result) return;
    try {
      const { default: jsPDF } = await import('jspdf');
      const doc = new jsPDF();
      const level = result.level === 'danger' ? 'HIGH RISK' : result.level === 'warning' ? 'MODERATE RISK' : 'SAFE';
      doc.setFontSize(20);
      doc.setTextColor(40, 35, 80);
      doc.text('DebtTrap Scanner — Financial Report', 20, 25);
      doc.setFontSize(11);
      doc.setTextColor(100);
      doc.text(`Generated on ${new Date().toLocaleDateString('en-IN', { dateStyle: 'long' })}`, 20, 33);
      doc.setDrawColor(61, 56, 117);
      doc.line(20, 37, 190, 37);
      doc.setFontSize(14);
      doc.setTextColor(40, 35, 80);
      doc.text('Risk Assessment', 20, 48);
      doc.setFontSize(12);
      doc.setTextColor(result.level === 'danger' ? 220 : result.level === 'warning' ? 180 : 20,
        result.level === 'danger' ? 50 : result.level === 'warning' ? 120 : 150, 50);
      doc.text(`Status: ${level}`, 20, 57);
      doc.setTextColor(60);
      doc.setFontSize(11);
      const metrics = [
        ['New Monthly EMI', `₹${result.newEMI.toLocaleString()}`],
        ['Total EMI Burden', `₹${result.totalEMI.toLocaleString()}/month`],
        ['Free Cash After EMIs', `₹${result.freeCash.toLocaleString()}/month`],
        ['Debt-to-Income Ratio', `${result.dti}% (safe limit: 35%)`],
        ['Total Interest Payable', `₹${result.totalInterest.toLocaleString()}`],
        ['Cashflow Negative From', result.insolventMonth !== -1 ? `Month ${result.insolventMonth}` : 'Does not go negative'],
      ];
      let y = 70;
      doc.setFontSize(14);
      doc.setTextColor(40, 35, 80);
      doc.text('Key Metrics', 20, y);
      y += 10;
      metrics.forEach(([key, val]) => {
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(key, 20, y);
        doc.setTextColor(40);
        doc.text(val, 110, y);
        y += 8;
      });
      y += 5;
      doc.line(20, y, 190, y);
      y += 10;
      doc.setFontSize(11);
      doc.setTextColor(80);
      doc.text('Recommendation', 20, y);
      y += 8;
      doc.setFontSize(10);
      doc.setTextColor(60);
      const advice = result.level === 'danger'
        ? 'Your debt-to-income ratio exceeds safe limits. Taking this loan significantly increases your financial risk.\nConsider reducing loan amount, increasing tenure, or paying off existing loans first.'
        : result.level === 'warning'
        ? 'Your finances are stretched but manageable. Build an emergency fund before committing to this loan.\nAvoid any additional credit in the next 12 months.'
        : 'Your debt load is within safe limits. Ensure you maintain consistent on-time payments to build your CIBIL score.';
      const lines = doc.splitTextToSize(advice, 170);
      doc.text(lines, 20, y);
      y += lines.length * 6 + 10;
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text('Generated by DebtTrap Scanner — Know before you borrow. Not financial advice.', 20, 285);
      doc.save('debttrap-report.pdf');
    } catch (err) {
      console.error('PDF export error:', err);
    }
  };

  return (
    <div className="page-split">
      <InputPanel
        income={income} setIncome={setIncome}
        expenses={expenses} setExpenses={setExpenses}
        loans={loans} addLoan={addLoan} removeLoan={removeLoan}
        newAmount={newAmount} setNewAmount={setNewAmount}
        newRate={newRate} setNewRate={setNewRate}
        newTenure={newTenure} setNewTenure={setNewTenure}
        onCalculate={calculate}
      />
      <div ref={resultRef} style={{ display: 'flex', flexDirection: 'column' }}>
        <ResultPanel result={result} />
        {result && (
          <div style={{ padding: '0 2rem 2rem' }}>
            <button onClick={exportPDF} style={{
              width: '100%', padding: '12px', background: 'transparent',
              border: '1.5px solid var(--border2)', borderRadius: '12px',
              fontSize: '13px', fontWeight: '500', color: 'var(--text2)',
              cursor: 'pointer', fontFamily: 'Plus Jakarta Sans, sans-serif',
              display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px',
              transition: 'all 0.2s', marginTop: '10px',
            }}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                <polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
              </svg>
              Export PDF Report
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
